---
- name: Workaround missing items in sections for placement and neutron
  # workaround for this https://paste.opendev.org/show/816007
  gather_facts: false
  hosts: localhost ansible_connection=local
  vars:
    my_file: /home/stack/ext/tripleo-ansible/tripleo_ansible/inventory/99-custom
    my_ini: /var/lib/config-data/ansible-generated/nova_libvirt/etc/nova/nova.conf
  tasks:
    - name: Add missing placement key/values to nova.conf (like LP 1850691)
      become: true
      ini_file:
        path: "{{ my_ini }}"
        create: false
        backup: false
        section: 'placement'
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: 'auth_type', value: 'password' }
        - { key: 'project_name', value: 'service' }
        - { key: 'project_domain_name', value: 'Default' }
        - { key: 'username', value: 'placement' }
        - { key: 'user_domain_name', value: 'Default' }
        - { key: 'valid_interfaces', value: 'internal' }
        - { key: 'region_name', value: 'regionOne' }
    - name: Add missing neutron key/values to nova.conf
      become: true
      ini_file:
        path: "{{ my_ini }}"
        create: false
        backup: false
        section: 'neutron'
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: 'auth_type', value: 'v3password' }
        - { key: 'project_name', value: 'service' }
        - { key: 'user_domain_name', value: 'Default' }
        - { key: 'project_domain_name', value: 'Default' }
        - { key: 'region_name', value: 'regionOne' }
        - { key: 'username', value: 'neutron' }
        - { key: 'valid_interfaces', value: 'internal' }
