---
- name: Workaround missing vars under neutron service_user libvirt
  # workaround for these errors: https://paste.opendev.org/show/bOipV0vIWrffm1IHlbAE/
  gather_facts: false
  hosts: localhost ansible_connection=local
  vars:
    my_ini: /var/lib/config-data/ansible-generated/nova_libvirt/etc/nova/nova.conf
  tasks:
    - include_vars: /home/stack/ceph_client.yaml
    - name: Add missing rbd libvirt key/values to nova.conf
      become: true
      ini_file:
        path: "{{ my_ini }}"
        create: false
        backup: false
        section: 'libvirt'
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: 'rbd_secret_uuid', value: "{{ tripleo_ceph_client_fsid }}" }
        - { key: 'images_rbd_ceph_conf', value: '/etc/ceph/ceph.conf' }
        - { key: 'images_rbd_glance_copy_poll_interval', value: '15' }
        - { key: 'images_rbd_glance_copy_timeout', value: '600' }
        - { key: 'images_rbd_glance_store_name', value: 'default_backend' }
        - { key: 'images_rbd_pool', value: 'vms' }
        - { key: 'images_type', value: 'rbd' }
        - { key: 'rbd_user', value: 'openstack' }
