---
- name: Workaround missing items in sections for neutron and service_user
  # workaround for these errors: https://paste.opendev.org/show/bOipV0vIWrffm1IHlbAE/
  gather_facts: false
  hosts: localhost ansible_connection=local
  vars:
    #my_file: /home/stack/ext/tripleo-ansible/tripleo_ansible/inventory/99-custom
    #placement_password: "{{ lookup('ini', 'tripleo_nova_compute_placement_password section=Compute:vars file=' ~ my_file) }}"
    my_ini: /var/lib/config-data/ansible-generated/nova_libvirt/etc/nova/nova.conf
  tasks:
    - name: Add missing neutron key/values to nova.conf
      become: true
      ini_file:
        path: "{{ my_ini }}"
        create: false
        backup: false
        section: 'neutron'
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: 'auth_type', value: 'v3password' }
        - { key: 'project_name', value: 'service' }
        - { key: 'user_domain_name', value: 'Default' }
        - { key: 'project_domain_name', value: 'Default' }
        - { key: 'region_name', value: 'regionOne' }
        - { key: 'username', value: 'neutron' }
    - name: Add missing service_user key/values to nova.conf
      become: true
      ini_file:
        path: "{{ my_ini }}"
        create: false
        backup: false
        section: 'service_user'
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: 'username', value: 'nova' }
